### ISSUE TITLE
laterpay/views/backend/pricing.php

### ISSUE THREAD

**Issue by tomjn** [rtCamp/laterpay-wordpress-plugin#10]
Missing escaping, the best solution would be for `render_time_pass` to output internally, making this a non-issue:

```
echo $this->render_time_pass( $pass ) //phpcs:ignore
```

Missing escaping:

```
echo $this->render_time_pass()
```

Missing escaping:

```
echo $this->render_subscription( $subscription )
```

Missing escaping:

```
echo $this->render_subscription()
```

----

Most of these would be resolved by moving the output inside the function rather than returning it as a variable

**Comment by PatelUtkarsh** [comment]
Some of these methods are used in ajax so I added a param for echo.
