### ISSUE TITLE
Dispatcher output

### ISSUE THREAD

**Issue by tomjn** [rtCamp/laterpay-wordpress-plugin#3]
In `application/Core/Event/Dispatcher.php` there's the question of escaping here:

```
        if ( $event->is_echo_enabled() ) {
            // todo: Check if output needs escaping if HTML
            echo $event->get_formatted_result(); // phpcs:ignore
```

Ideally it would echo internally and task responsibility for escaping rather than handing it to the dispatcher, but I understand that events collect HTML strings as they're passed around, so it doesn't help a lot

There's also the filter problem just beforehand:

```
        // apply registered in wordpress filters for the event result
        $result = LaterPay_Hooks::apply_filters( $event_name, $event->get_result() );
        $event->set_result( $result );
```

Even if the result can be trusted, which it can't, these lines undo that by applying "mystery sauce"

**Comment by PatelUtkarsh** [comment]
@tomjn I am working on a PR which will echo directly in event for html callbacks events.

```
$result = LaterPay_Hooks::apply_filters( $event_name, $event->get_result() );
```

This code allows other plugin to access laterpay's data and inject their data to it.
After echoing html events directly it will only able to access ajax request's data.

Would that be okay?

**Comment by tomjn** [comment]
You mean it can only access the AJAX data so that it can do its own output? I'm not sure I understand correctly

**Comment by PatelUtkarsh** [comment]
Check PR, It should fix the early escaping issue for html views. @tomjn

**Comment by tomjn** [comment]
I'm reopening this as there's additional places that rely on the same pattern, namely of an event object being passed around collecting HTML as it goes along ( or in financial risk speak, collecting liability and risk then depositing it all at once ).

I'm apprehensive as it's difficult to apply the rule that we can append `__escaped` or `__safe` to variables. Ideally hooks/actions would be used to wrap things. On top of that, there's a few cases were the end result is passed through `wp_kses_post` making it safe. I'm not sure if the final result of something is going to be escaped or if it's intended to be escaped on creation.

To avoid a refactor, is it possible that a version of `wp_kses` with some additional tags such as `div` etc but not `iframe` or `script` would do the trick? I'm keen to avoid code churn that would see half the files light up in my tooling as unreviewed due to single line changes, and make progress efficiently

**Comment by tomjn** [comment]
In particular I'm still unsure of this code in the dispatcher class:

```
        // apply registered in wordpress filters for the event result
        $result = LaterPay_Hooks::apply_filters( $event_name, $event->get_result() );
        $event->set_result( $result );
        if ( $event->is_echo_enabled() && $event->is_ajax() ) {
            echo $event->get_formatted_result(); // phpcs:ignore
	        die;
        }
```

**Comment by tomjn** [comment]
One more exotic solution might be that instead of setting the 'result' and giving it HTML, to instead pass closures and lambda functions that output internally. These can then be appended to the start or end, or removed. Instead of collecting HTML fragments, the event would collect HTML renderers, with each late escaping and outputting on demand

**Comment by PatelUtkarsh** [comment]
@tomjn
> is it possible that a version of wp_kses with some additional tags. 

I think this will result in double escape in most cases. 

>Pass closures and lambda functions that output internally

This will be cool solution but it will make this more complex.

-----

Echo is for the ajax request and all HTML in array value are escaped in it.

`echo $event->get_formatted_result(); // phpcs:ignore` 
We can replace above line with `echo wp_json_encode( $event->get_result() );` if echo is the problem.

Alternatively, We can remove that echo line and let ajax callback print the response if possible for all ajax request.

**Comment by tomjn** [comment]
`wp_kses` is the exception to the double escaping rule as it removes but doesn't modify/mangle, it's technically a sanitizing function rather than an escaping function. You can pass it over output as many times as you'd like, the downside being that `wp_kses_post(wp_kses_post(wp_kses_post(wp_kses_post(wp_kses_post($content )))))` is slower


> Alternatively, We can remove that echo line and let ajax callback print the response if possible for all ajax request.

That works too, as does `echo wp_json_encode( $event->get_result() );`
